version: '3.9'

services:
  db:
    image: mysql
    container_name: Spring-DataJpa_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - Spring-DataJpa:/var/lib/mysql
volumes:
  Spring-DataJpa: {}